### ISSUE TITLE
mcf2pdf startup script must be invoked in installation directory

### ISSUE THREAD

**Issue by albrechtf** [albrechtf/mcf2pdf#14]
Currently, both Windows and Linux / Mac versions of the startup script assume that the directory of the mcf2pdf JAR file is the current directory. 

There are techniques both for Windows and for Linux to determine the directory of the script, and include it in the path of the JAR file in the Java Classpath. These should be included in both scripts.

**Comment by focusnum** [comment]
i move .mcf file and photos in the same folder of mcf2pdf and i have this message now...
Mini-de-Renaud:mcf2pdf-0.3.2 renaud$ ./mcf2pdf /Users/renaud/Downloads/mcf2pdf-0.3.2/NY-2016.mcf output.pdf
[ERROR] net.sf.mcf2pdf.Main An exception has occured
java.io.IOException: MCF Resources Directory /Applications/Atelier Photo Fnac.app/Resources does not exist
at net.sf.mcf2pdf.Mcf2FoConverter.(Mcf2FoConverter.java:94)
at net.sf.mcf2pdf.Main.main(Main.java:181)

**Comment by focusnum** [comment]
I think, the path is not correct. On my mac i think the correct path is

/Applications/Atelier\ Photo\ Fnac.app/Contents/Resources (this is from my Terminal)

**Comment by albrechtf** [comment]
You must specify the full path in the startup script, as specified in the README at https://github.com/albrechtf/mcf2pdf. Please note that the path is case sensitive on Linux and Mac. Spaces in the path are always a bad idea :-) 

Try to specify the full path to the "Contents" directory as MCF installation directory, as mcf2pdf checks for a "Resources" subdirectory of the installation directory. As mcf2pdf is untested for Mac (and officially unsupported), you will have to figure it out by yourself, unfortunately...

By the way, this problem is unrelated to this issue.

**Comment by focusnum** [comment]
Hello, thank you for the answer.
I will try to write the real path in the script !

**Comment by focusnum** [comment]
hello i change the name of the folder that content MCF software, but i still have the problem.
In the script, i write
MCF_INSTALL_DIR=/Applications/Atelier_Photo_Fnac.app 
(path is coming from the terminal, so i presum it's right)

but the script return me an error, the same : 
Mini-de-Renaud:mcf2pdf-0.3.2 renaud$ ./mcf2pdf /Users/renaud/Downloads/mcf2pdf-0.3.2/NY-2016.mcf output.pdf
[ERROR] net.sf.mcf2pdf.Main An exception has occured
java.io.IOException: MCF Resources Directory /Applications/Atelier_Photo_Fnac.app/Resources does not exist
	at net.sf.mcf2pdf.Mcf2FoConverter.<init>(Mcf2FoConverter.java:94)
	at net.sf.mcf2pdf.Main.main(Main.java:181)

i think that the script is trying to find something at /Resources but the real path is
/Applications/Atelier_Photo_Fnac.app/Contents/Resources

with /Contents/
no ?
sorry my so poor english and thank you for your time

**Comment by focusnum** [comment]
how can i change this path ?

**Comment by focusnum** [comment]
OK :)
so i change the path to 
/Applications/Atelier_Photo_Fnac.app/Contents/Resources
and it's work...a little bit more,
but now i have this long message

Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at java.awt.image.DataBufferByte.<init>(DataBufferByte.java:92)
	at java.awt.image.ComponentSampleModel.createDataBuffer(ComponentSampleModel.java:445)
	at java.awt.image.Raster.createWritableRaster(Raster.java:941)
	at javax.imageio.ImageTypeSpecifier.createBufferedImage(ImageTypeSpecifier.java:1074)
	at javax.imageio.ImageReader.getDestination(ImageReader.java:2892)
	at com.sun.imageio.plugins.jpeg.JPEGImageReader.readInternal(JPEGImageReader.java:1071)
	at com.sun.imageio.plugins.jpeg.JPEGImageReader.read(JPEGImageReader.java:1039)
	at javax.imageio.ImageIO.read(ImageIO.java:1448)
	at javax.imageio.ImageIO.read(ImageIO.java:1308)
	at net.sf.mcf2pdf.mcfelements.util.ImageUtil.readImage(ImageUtil.java:78)
	at net.sf.mcf2pdf.pagebuild.PageImage.renderAsBitmap(PageImage.java:82)
	at net.sf.mcf2pdf.pagebuild.BitmapPageBuilder.addToDocumentBuilder(BitmapPageBuilder.java:77)
	at net.sf.mcf2pdf.Mcf2FoConverter.convert(Mcf2FoConverter.java:211)
	at net.sf.mcf2pdf.Main.main(Main.java:181)

any idea ?
thank you

**Comment by albrechtf** [comment]
For the Out Of Memory, please refer to the README / Troubleshooting section. I will have to delete your comments here, as they are unrelated to this issue. If you encounter other problems which may be a bug (and after reading the whole README), feel free to create another issue.

**Comment by focusnum** [comment]
No problem, sorry for my tons of questions...

**Comment by focusnum** [comment]
YES !!
I'ts working !!!
Thank you ! Thank you very much for your support.
SO it's working on Mac OS X !
You did excellent work, thank you for helping people, it's great
