### ISSUE TITLE
File is not the correct format

### ISSUE THREAD

**Issue by ptibilou** [albrechtf/mcf2pdf#22]
Hi,

Iv'got a bug when converting a mcf file :
Log : http://pastebin.com/stiUbFZR
Mcf : http://pastebin.com/qgECi9XD

The mcf have been created with pixum, opend and re-saved with cewe.

Thx

Etienne

**Comment by aschafu** [comment]
I have the same error -- file produced with "Meine CEWE Fotowelt 6.2.4" on Mac.

[ERROR] net.sf.mcf2pdf.Main An exception has occured
java.io.IOException: com.drew.imaging.ImageProcessingException: File is not the correct format
	at net.sf.mcf2pdf.mcfelements.util.ImageUtil.getImageRotation(ImageUtil.java:119)
	at net.sf.mcf2pdf.mcfelements.util.ImageUtil.readImage(ImageUtil.java:77)
	at net.sf.mcf2pdf.pagebuild.PageImage.renderAsBitmap(PageImage.java:81)
	at net.sf.mcf2pdf.pagebuild.BitmapPageBuilder.addToDocumentBuilder(BitmapPageBuilder.java:77)
	at net.sf.mcf2pdf.Mcf2FoConverter.convert(Mcf2FoConverter.java:240)
	at net.sf.mcf2pdf.Main.main(Main.java:181)
Caused by: com.drew.imaging.ImageProcessingException: File is not the correct format
	at com.drew.imaging.ImageMetadataReader.readMetadata(Unknown Source)
	at com.drew.imaging.ImageMetadataReader.readMetadata(Unknown Source)
	at net.sf.mcf2pdf.mcfelements.util.ImageUtil.getImageRotation(ImageUtil.java:100)

**Comment by aschafu** [comment]
Oh, but I just noticed I had used a png version of an image instead of jpeg. After replacing that, everything goes smoothly. Thanks for the great work!

**Comment by albrechtf** [comment]
Please re-check if issue persists with latest version 0.3.3: https://github.com/albrechtf/mcf2pdf/releases/tag/mcf2pdf-0.3.3 Thanks!
