### ISSUE TITLE
Script does not work with cewe Ver 6.2.3

### ISSUE THREAD

**Issue by OlliGoLeer** [albrechtf/mcf2pdf#24]
Hi,
does the script not work with cewe Ver 6.2.3?
I am getting numerous errors
I used mcf2pdf some month before without any issues.
Any Idea?

**Comment by albrechtf** [comment]
Could you please paste your "numerous errors" here? That would help a lot. There is a high chance that something changed (again) in the format...

**Comment by rbodziony** [comment]
Hi 
 Problem are 2...
1) now border got color stored in this way 
...
<border color="#ff000000"
....
version before were
<border color="#000000"
...
....
stacktrace looks like 
....
lineNumber: 14; columnNumber: 90; Error at line 14 char 90: Error converting from 'String' to 'java.awt.Color' For input string: "ff000000"
        at org.apache.commons.digester3.Digester.createSAXException(Digester.java:3118)
        at org.apache.commons.digester3.Digester.createSAXException(Digester.java:3146)
        at org.apache.commons.digester3.Digester.startElement(Digester.java:1355)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanStartElement(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
        at org.apache.commons.digester3.Digester.parse(Digester.java:1642)
        at org.apache.commons.digester3.Digester.parse(Digester.java:1588)
        at net.sf.mcf2pdf.mcfelements.FotobookBuilder.readFotobook(FotobookBuilder.java:56)
        at net.sf.mcf2pdf.Mcf2FoConverter.convert(Mcf2FoConverter.java:154)
        at net.sf.mcf2pdf.Main.main(Main.java:181)
....
2) all images in photo were converted to .webp

**Comment by rbodziony** [comment]
https://github.com/corinis/mcf2pdf/commit/a917479b0c915cd05137c7cc48c3cd2151a2f69a

**Comment by OlliGoLeer** [comment]
Hi albrechtf,

here is the error list.

I hope you can help ;)

[ERROR] net.sf.mcf2pdf.Main An exception has occured
org.xml.sax.SAXParseException; systemId: file:/D:/AAA/fb1.mcf; lineNumber: 14; columnNumber: 90; Error at line 14 char 90: Error converting from 'String' to 'java.awt.Color' For input string: "ff000000"
        at org.apache.commons.digester3.Digester.createSAXException(Digester.java:3118)
        at org.apache.commons.digester3.Digester.createSAXException(Digester.java:3146)
        at org.apache.commons.digester3.Digester.startElement(Digester.java:1355)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanStartElement(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
        at org.apache.commons.digester3.Digester.parse(Digester.java:1642)
        at org.apache.commons.digester3.Digester.parse(Digester.java:1588)
        at net.sf.mcf2pdf.mcfelements.FotobookBuilder.readFotobook(FotobookBuilder.java:56)
        at net.sf.mcf2pdf.Mcf2FoConverter.convert(Mcf2FoConverter.java:154)
        at net.sf.mcf2pdf.Main.main(Main.java:181)
Caused by: org.apache.commons.beanutils.ConversionException: Error converting from 'String' to 'java.awt.Color' For input string: "ff000000"
        at org.apache.commons.beanutils.converters.AbstractConverter.handleError(AbstractConverter.java:267)
        at org.apache.commons.beanutils.converters.AbstractConverter.convert(AbstractConverter.java:164)
        at org.apache.commons.beanutils.ConvertUtilsBean.convert(ConvertUtilsBean.java:470)
        at org.apache.commons.beanutils.BeanUtilsBean.setProperty(BeanUtilsBean.java:1006)
        at org.apache.commons.beanutils.BeanUtilsBean.populate(BeanUtilsBean.java:830)
        at org.apache.commons.beanutils.BeanUtils.populate(BeanUtils.java:433)
        at org.apache.commons.digester3.SetPropertiesRule.begin(SetPropertiesRule.java:232)
        at org.apache.commons.digester3.Digester.startElement(Digester.java:1350)
        ... 16 more
Caused by: java.lang.NumberFormatException: For input string: "ff000000"
        at java.lang.NumberFormatException.forInputString(Unknown Source)
        at java.lang.Integer.parseInt(Unknown Source)
        at java.lang.Integer.valueOf(Unknown Source)
        at java.lang.Integer.decode(Unknown Source)
        at java.awt.Color.decode(Unknown Source)
        at net.sf.mcf2pdf.mcfelements.impl.DigesterConfiguratorImpl$1.convertToType(DigesterConfiguratorImpl.java:63)
        at org.apache.commons.beanutils.converters.AbstractConverter.convert(AbstractConverter.java:156)

**Comment by h-david-a** [comment]
@rbodziony 
> corinis/mcf2pdf@a917479

Nope, it doesn't work: 
Cewe 6.2.3
Warning: Could not get charToByteConverterClass!
And no text in output PDF (pics are ok)

**Comment by rbodziony** [comment]
this fix from cornis fixing Color issue i dont know about no text issue

**Comment by h-david-a** [comment]
I've narrowed text issue:
During conversion "Calibri" font from .mcf file is replaced by some other one. And that new one doesn't contain cyrilic chars :(

**Comment by rbodziony** [comment]
can you paste sample 
<text...
</text>
what not works
for me for example dont works 
font="MS Shell Dlg 2,12,-1,5,50,0,0,0,0,0" (missing special chars cyrilic ) calibri works for me !

**Comment by h-david-a** [comment]
Issue with font difference fixed by re-applying font family in the app (strange, that app displayed it as "Calibri", but in sources it was indeed "MS Shell Dlg" .
Now source looks like this:
 ` <area height="1419" width="1189.738267259861" rotation="0" left="2808.394160583941" zposition="1000" areatype="textarea" top="602.3809523809523" isResizable="1" alpha="1" applySpotColor="0">
   <border position="inside" enabled="0" width="5" applySpotColor="1" color="#ff000000"/>
   <text isSpineText="0" areaTextType="all"><![CDATA[<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd"><html><head><meta name="qrichtext" content="1" /><style type="text/css">p, li { white-space: pre-wrap; }</style></head><body style=" font-family:'Calibri'; font-size:11pt; font-weight:400; font-style:normal;"><p align="justify" style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Жила была на свете Белая Шляпа и была она такая любопытная, что не сиделось ей на месте. &quot;А зачем сидеть на месте, когда мир такой большой, необыкновенно красиво заманчивый, столько загадок вокруг, историй и тайн?&quot; - так любила повторять Белая Шляпа, и конечно же в чем-то она была права.<span style=" font-size:8.25pt;"> </span></p><p align="justify" style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">У Белой Шляпы была закадычная подруга, очень похожая на нее, Белая Луна. Они частенько собирались вместе за чашкой душистого капучино обсудить что, где, когда, зачем и почему. Обычно их разговор начинался с того, что Белая Шляпа высовывала свой любопытный нос из окна, смотрела в небо и говорила их т</p><p align="justify" style="-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><br /></p><p align="justify" style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">TEST IN THE MIDDLE</p><p align="justify" style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">ило под полями от нетерпения поскорее узнать где же на этот раз побывала ее загадочная подруга. Белая Шляпа начала подпрыгивать от нетерпения, а Белая Луна ничего не сказала, а только еще таинственней улыбнулась и подмигнула куда-то в сторону южной Италии, провинции Апулия, ярко-бирюзового моря, необыкновенно синего неaба, сонной тишины вековых оливок, душистого и терпкого запаха оливкового масла, теплой фокаччи с вялеными помидорами, доброго домашнего вина и всего-всего-всего от чего в носу становится необыкновенно щекотно, рот наполняется слюной и хочется поскорее все это попробовать, вдохнуть, закрыть глаза и со счастливой улыбкой смотреть на синее небо. Белая Шляпа посмотрела вокруг, недалеко от ее дома находился аэропорт, она бросила в сумку все самое необходимое и усевшись в мягкое кресло салона, тихо мурлыкая себе под нос Феличита... Блаженно прикрыла глаза. </p></body></html>]]><outline enabled="0" width="1" color="#ff000000"/>
    <textFormat IndentMargin="4" Alignment="ALIGNJUSTIFY" font="Calibri,11,-1,5,50,0,0,0,0,0" VerticalIndentMargin="0" backgroundColor="#00000000" hasOutline="0" foregroundColor="#ff000000"/>
   </text>
  </area>
  <area height="226.130997193895" width="1008.007665457532" rotation="0" left="2955.033878584628" zposition="1001" areatype="textarea" top="206.9673533639039" isResizable="1" alpha="1" applySpotColor="0">
   <border position="outside" enabled="0" width="2" applySpotColor="0" color="#ff000000"/>
   <text isSpineText="0" areaTextType="all"><![CDATA[<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd"><html><head><meta name="qrichtext" content="1" /><style type="text/css">p, li { white-space: pre-wrap; }</style></head><body style=" font-family:'Calibri'; font-size:11pt; font-weight:400; font-style:normal;"><p align="justify" style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" color:#000000;">non-cyrylic text</span></p></body></html>]]><outline enabled="0" width="1" color="#ff000000"/>
    <textFormat IndentMargin="4" Alignment="ALIGNJUSTIFY" font="Calibri,11,-1,5,50,0,0,0,0,0" VerticalIndentMargin="0" backgroundColor="#00000000" hasOutline="0" foregroundColor="#ff000000"/>
   </text>
  </area>`


And displayed in app like this:
![image](https://user-images.githubusercontent.com/8490816/28207416-f46d980c-6889-11e7-9f79-5be99da89c90.png)
Whereas rendered to PDF like this:
![image](https://user-images.githubusercontent.com/8490816/28207438-05e1908e-688a-11e7-90cc-4fe3653f8929.png)

**Comment by rbodziony** [comment]
did you tried use fork version from corinis (niko) he changed rending texts so maybe his fork for cyrilic is better then main ?

**Comment by h-david-a** [comment]
didn't manage even to run it :(

I'm lost abit with versioning:
there's original version by albrechtf. Which is quite outdated and doesn't support RGBA color scheme
then forked by okworx (with "disable page blending" option) [https://github.com/okworx/mcf2pdf](url)
and then forked by corinis from okworx (with RGBA support) [https://github.com/corinis/mcf2pdf](url)

I've ended up using original version by albrechtf with RGBA modification: corinis/mcf2pdf@a917479

**Comment by h-david-a** [comment]
So, I took https://github.com/okworx/mcf2pdf and applied corinis/mcf2pdf@a917479
result is exactly the same: cyrilic text is not rendered

After playing around with source .mcf file, I've noticed that text is not rendered if sequence `<p><span style=" color:#000000;">%CYRILIC TEXT%</span></p>` is not followed. E.g:
1. `<span>` tag is omitted: just `<p> TEXT </p>`
2. `<span>` tag is 'streched' over several `<p>` tags. 
    `<p><span>TEXT</p><p>TEXT</span></p>` OR
    `<span><p>TEXT</p><p>TEXT</p></span>`

Newly created files do not have this issue.
Wokaround for existing files is to open file in CEWE App, select text in existing text box, and change properties via settings dialogue (and click "apply to all texts in project")
![image](https://user-images.githubusercontent.com/8490816/28250417-e5750a94-6a67-11e7-8d1a-d7a8a91e52dc.png)

Btw. Mystery of "MS Shell Dlg 2" is also resolved. It is virtual font. Technical info on MSDN: [https://msdn.microsoft.com/en-us/library/windows/desktop/dd374112(v=vs.85).aspx](url)
Real font value could be checked via Regedit:
`[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\FontSubstitutes]
"MS Shell Dlg"="Microsoft Sans Serif"
"MS Shell Dlg 2"="Tahoma"`
Or with PowerShell oneliner:
`Get-Item "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\FontSubstitutes\"|get-itemproperty|select -ExpandProperty "MS Shell Dlg 2"`

**Comment by OlliGoLeer** [comment]
very technical information ....
any advice for a noob? will there be a new version of this project that works with latest cewe version?

**Comment by rbodziony** [comment]
try use my forked version dunno when albert will release new version 
https://github.com/rbodziony/mcf2pdf/commit/b3cf8bccbddeeb2222fff653155532f69234fa63

**Comment by h-david-a** [comment]
Btw, your version doesn't stick background images correctly :( there's
whitespace between

regards, David Khotiun

25 июля 2017 г. 2:48 PM пользователь "rbodziony" <notifications@github.com>
написал:

**Comment by rbodziony** [comment]
But text now are cyrilic right ?
and clp/svg clips now works ?
can you paste example based on test/resorces/*.mcf ?
Regards,
 Robert

**Comment by rbodziony** [comment]
![image](https://user-images.githubusercontent.com/29715596/28579603-6137a60e-715d-11e7-8558-01f041ccfcd1.png)

**Comment by h-david-a** [comment]
>But text now are cyrilic right ?
Yes. As I wrote previously, there were 2 things why Cyrillic was not
displayed: 1. Wrong file contents (maybe due to version changes) 2. Default
font (which was set by app) didn't have Cyrillic chars

>and clp/svg clips now works ?

Haven't tried. JPEGs are ok

>can you paste example based on test/resorces/*.mcf ?

I'll create samples and post them.

regards, David Khotiun

25 июля 2017 г. 5:14 PM пользователь "rbodziony" <notifications@github.com>
написал:

But text now are cyrilic right ?
and clp/svg clips now works ?
can you paste example based on test/resorces/*.mcf ?
Regards,
Robert

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/albrechtf/mcf2pdf/issues/24#issuecomment-317770697>,
or mute
the thread

**Comment by albrechtf** [comment]
Sorry guys to interrupt you here. Please continue discussion about issues and features of **forks** on the fork's GitHub page, not here.

Thanks to all contributors for the new Pull Requests. Unfortunately I've got very little time at the moment to review & merge them. I will try in August. Please be patient (or use the forks - or fork by yourself and apply the patches :-)).

The Software (not a **script**, sorry for being tetchy there) currently does obviously not support the latest CEWE version. Acknowledged, so for now, I will close this issue and reopen it to mark it as being fixed as soon as time permits. Thank you for your understanding!

**Comment by albrechtf** [comment]
Just discovered the "Lock conversation" button. Much more appropriate :-)

**Comment by albrechtf** [comment]
Please check your initial issue against latest release: https://github.com/albrechtf/mcf2pdf/releases/tag/mcf2pdf-0.3.3. Feel free to open new issues for any remaining problems. Thanks!
