### ISSUE TITLE
Files\CEWE\CEWE was unexpected at this time.

### ISSUE THREAD

**Issue by btontheway** [albrechtf/mcf2pdf#36]
Hi there,
I get the following message:
Files\CEWE\CEWE was unexpected at this time.
The full folder, what I have set up at the bat file was:
SET MCF_INSTALL_DIR="D:\Program Files\CEWE\CEWE Fotovilag"
Could you please help me if you know what I should to in order to generate my pdf files?
Thanks, Tamas

**Comment by wulmer** [comment]
The correct syntax would be

    set "MCF_INSTALL_DIR=D:\Program Files\CEWE\CEWE Fotovilag"

Make sure to put the quotes around the whole argument to `set`.

**Comment by btontheway** [comment]
Thank yo. I got further...
This is now the message I get. May be you have an idea where the problem can be...

f2pdf-0.3.4-bin-windows/mcf2pdf-0.3.4/lib/batik-gui-util-1.7.jar, file:/C:/Users/borost/Downloads/mcf2pdf-0.3.4-bin-windows/mcf2pdf-0.3.4/lib/xml-apis-ext-1.3.04.jar, file:/C:/Users/borost/Downloads/mcf2pdf-0.3.4-bin-windows/mcf2pdf-0.3.4/lib/batik-codec-1.7.jar, file:/C:/Users/borost/Downloads/mcf2pdf-0.3.4-bin-windows/mcf2pdf-0.3.4/lib/commons-digester3-3.1.jar, file:/C:/Users/borost/Downloads/mcf2pdf-0.3.4-bin-windows/mcf2pdf-0.3.4/lib/commons-logging-1.1.1.jar, file:/C:/Users/borost/Downloads/mcf2pdf-0.3.4-bin-windows/mcf2pdf-0.3.4/lib/commons-beanutils-1.8.3.jar, file:/C:/Users/borost/Downloads/mcf2pdf-0.3.4-bin-windows/mcf2pdf-0.3.4/lib/commons-cli-1.2.jar, file:/C:/Users/borost/Downloads/mcf2pdf-0.3.4-bin-windows/mcf2pdf-0.3.4/lib/log4j-1.2.9.jar, file:/C:/Users/borost/Downloads/mcf2pdf-0.3.4-bin-windows/mcf2pdf-0.3.4/lib/jempbox-1.6.0.jar, file:/C:/Users/borost/Downloads/mcf2pdf-0.3.4-bin-windows/mcf2pdf-0.3.4/lib/metadata-extractor-2.9.1.jar, file:/C:/Users/borost/Downloads/mcf2pdf-0.3.4-bin-windows/mcf2pdf-0.3.4/lib/xmpcore-5.1.2.jar, file:/C:/Users/borost/Downloads/mcf2pdf-0.3.4-bin-windows/mcf2pdf-0.3.4/lib/pngj-2.1.0.jar, file:/C:/Users/borost/Downloads/mcf2pdf-0.3.4-bin-windows/mcf2pdf-0.3.4/lib/jna-4.1.0.jar, file:/C:/Users/borost/Downloads/mcf2pdf-0.3.4-bin-windows/mcf2pdf-0.3.4/lib/jna-platform-4.1.0.jar, file:/C:/Users/borost/Downloads/mcf2pdf-0.3.4-bin-windows/mcf2pdf-0.3.4/lib/junit-4.11.jar, file:/C:/Users/borost/Downloads/mcf2pdf-0.3.4-bin-windows/mcf2pdf-0.3.4/lib/hamcrest-core-1.3.jar, file:/C:/Users/borost/Downloads/mcf2pdf-0.3.4-bin-windows/mcf2pdf-0.3.4/lib/jai-imageio-core-1.3.0.jar, file:/D:/Program%20Files/CEWE/CEWE%20Fotovilag/, file:/C:/Users/borost/Downloads/mcf2pdf-0.3.4-bin-windows/mcf2pdf-0.3.4/mcf2pdf-0.3.4.jar])
        at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:271)
        at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:398)
        at com.sun.jna.Library$Handler.<init>(Library.java:147)
        at com.sun.jna.Native.loadLibrary(Native.java:412)
        at com.sun.jna.Native.loadLibrary(Native.java:391)
        at net.sf.mcf2pdf.mcfelements.util.webp.Webp.loadLibrary(Webp.java:42)
        at net.sf.mcf2pdf.mcfelements.util.ImageUtil.internalRead(ImageUtil.java:267)
        at net.sf.mcf2pdf.mcfelements.util.ImageUtil.readImage(ImageUtil.java:84)
        at net.sf.mcf2pdf.pagebuild.PageBackground.drawBackground(PageBackground.java:76)
        at net.sf.mcf2pdf.pagebuild.PageBackground.renderAsBitmap(PageBackground.java:61)
        at net.sf.mcf2pdf.pagebuild.BitmapPageBuilder.addToDocumentBuilder(BitmapPageBuilder.java:77)
        at net.sf.mcf2pdf.Mcf2FoConverter.convert(Mcf2FoConverter.java:211)
        at net.sf.mcf2pdf.Main.main(Main.java:188)

**Comment by rbodziony** [comment]
Can you enable debug and provide log ?
