### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by gregwill** [albrechtf/mcf2pdf#43]
mcf2pdf 0.34 crashes with a NullPointerException for me.

[ERROR] net.sf.mcf2pdf.Main An exception has occured
java.lang.NullPointerException
	at net.sf.mcf2pdf.mcfglobals.McfResourceScanner.scanDirectory(McfResourceScanner.java:66)
	at net.sf.mcf2pdf.mcfglobals.McfResourceScanner.scanDirectory(McfResourceScanner.java:68)
	at net.sf.mcf2pdf.mcfglobals.McfResourceScanner.scanDirectory(McfResourceScanner.java:68)
	at net.sf.mcf2pdf.mcfglobals.McfResourceScanner.scanDirectory(McfResourceScanner.java:68)
	at net.sf.mcf2pdf.mcfglobals.McfResourceScanner.scan(McfResourceScanner.java:58)
	at net.sf.mcf2pdf.Mcf2FoConverter.<init>(Mcf2FoConverter.java:132)
	at net.sf.mcf2pdf.Main.main(Main.java:188)

Full output attached
[error.txt](https://github.com/albrechtf/mcf2pdf/files/1671563/error.txt)

**Comment by gregwill** [comment]
I read the source, and worked out that this must be some kind of special file type.  I'd set the MCF_TEMP_DIR to my Windows home directory that contains some "Library" folders.  When I changed it to an empty directory, the error went away.

It's probably worth adding a null-check to the code regardless, since I think the recursion of these directories can be skipped.

**Comment by paulerlm** [comment]
i think i have some similary problem with the nullpointerexception - still i don't know what to do. can someone please help me? 
[nullpointer.txt](https://github.com/albrechtf/mcf2pdf/files/3020168/nullpointer.txt)
