### ISSUE TITLE
parameter -b dont workx in ver 0.3.4: binding pages in each case (with/-out -b)

### ISSUE THREAD

**Issue by Nero6800** [albrechtf/mcf2pdf#56]
parameter -b dont workx in version 0.3.4 / CEWE 6.3.3: pages were binding in each case (with/-out -b)

**Comment by rbodziony** [comment]
Can you check this version https://github.com/rbodziony/mcf2pdf/releases/tag/0.3.7

**Comment by Nero6800** [comment]
Hello,

after installing Version 0.3.7 there is no result (PDF= 0 kb). Following is shown on the screen:
--------------------------------------------------------------------------------------------
 
D:\0>mcf2pdf.bat Kopie.mcf Kopie.pdf

[ERROR] net.sf.mcf2pdf.Main An exception has occured

org.xml.sax.SAXParseException; systemId: file:/D:/0/Kopie.mcf; lineNumber: 2; columnNumber: 185; Error at line 2 char 185: Error converting from 'String' to 'java.awt.Color' For input string: ""                    

        at org.apache.commons.digester3.Digester.createSAXException(Digester.java:3118)

        at org.apache.commons.digester3.Digester.createSAXException(Digester.java:3146)

        at org.apache.commons.digester3.Digester.startElement(Digester.java:1355)

        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(Unknown Source)

        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanStartElement(Unknown Source)

        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(Unknown Source)

        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(Unknown Source)

        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)

        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)

        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)

        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(Unknown Source)

        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(Unknown Source)

        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)

        at org.apache.commons.digester3.Digester.parse(Digester.java:1642)

        at org.apache.commons.digester3.Digester.parse(Digester.java:1588)

        at net.sf.mcf2pdf.mcfelements.FotobookBuilder.readFotobook(FotobookBuilder.java:56)

        at net.sf.mcf2pdf.Mcf2FoConverter.convert(Mcf2FoConverter.java:155)

        at net.sf.mcf2pdf.Main.main(Main.java:202)

Caused by: org.apache.commons.beanutils.ConversionException: Error converting from 'String' to 'java.awt.Color' For input string: ""

        at org.apache.commons.beanutils.converters.AbstractConverter.handleError(AbstractConverter.java:267)

        at org.apache.commons.beanutils.converters.AbstractConverter.convert(AbstractConverter.java:164)

        at org.apache.commons.beanutils.ConvertUtilsBean.convert(ConvertUtilsBean.java:470)

        at org.apache.commons.beanutils.BeanUtilsBean.setProperty(BeanUtilsBean.java:1006)

        at org.apache.commons.beanutils.BeanUtilsBean.populate(BeanUtilsBean.java:830)

        at org.apache.commons.beanutils.BeanUtils.populate(BeanUtils.java:433)

        at org.apache.commons.digester3.SetPropertiesRule.begin(SetPropertiesRule.java:232)

        at org.apache.commons.digester3.Digester.startElement(Digester.java:1350)

        ... 15 more

Caused by: java.lang.NumberFormatException: For input string: ""

        at java.lang.NumberFormatException.forInputString(Unknown Source)

        at java.lang.Integer.parseInt(Unknown Source)

        at java.lang.Integer.valueOf(Unknown Source)

        at java.lang.Integer.decode(Unknown Source)

        at java.awt.Color.decode(Unknown Source)

        at net.sf.mcf2pdf.mcfelements.impl.DigesterConfiguratorImpl$1.convertToType(DigesterConfiguratorImpl.java:77)

        at org.apache.commons.beanutils.converters.AbstractConverter.convert(AbstractConverter.java:156)

        ... 21 more

--------------------------------------------------------------------------------------------
Installed Java: 1.80 191-b12

Used for PDF (on D:\): Cewe6.3.3 

Also installed Pixum 6.4.1 (on C:)

Thx and greetings

**Comment by rbodziony** [comment]
Ok 
Thx for checking can you paste as code part of XML?

**Comment by Nero6800** [comment]
<fotobook imagedir="Kreta20142mcf_mcf-Dateien" designStyle="" productname="ALB72" savetime="2016-12-14 19:34" version="3.0" normalpages="34" pagenaming="1" productparameter="" productvariant_visiblename="" createdWithHPSVersion="5001007" startdatecalendarium="" programversion="6002001" useSpineLogo="0" identifier="7a4bab2f-c979-43a7-af4d-b675558638ac" compatibilityVersion="6001000" totalpages="39" isDataMcf="0" projectID="074fa4f9-833a-44f8-8a18-ee86cc8806c2" productvariant="pages:34" externalProjectId="">

<pagenumbering format="0" fontfamily="Arial" bgcolor="#" fontbold="0" textcolor="#000000" position="0" margin="110" fontitalics="0" textstring="%" verticalMargin="50" fontsize="12">

  <outline enabled="0" width="1"/>

</pagenumbering>

<extra>

  <lastTextFormat Alignment="ALIGNHCENTER" VerticalIndentMargin="50" IndentMargin="0" font="Bonita,16,-1,5,50,0,0,0,0,0" foregroundColor="#ffffff" hasOutline="0" backgroundColor="#000000"/>

</extra>

<page type="fullcover" rotation="0" pagenr="0">

  <bundlesize height="2750" width="4305"/>

  <designElementIDs background="201" layout="82069"/>

  <background type="1" rotation="0" alignment="4" templatename="Weiss,normal,"/>

  <background layout="1" templatename="fullcoverpage_portrait,normal"/>

  <area height="2950" zposition="1" shadowIntensity="128" top="-100" rotation="0" width="4505" shadowEnabled="0" shadowAngle="135" shadowDistance="50" areatype="imagebackgroundarea" shadowBlurNew="5" areaAbilities="6368" shadowWidthInMM="4" applySpotColor="0" left="-100" alpha="1">

   <border enabled="0" color="#000000" width="1" offset="1" applySpotColor="0"/>

   <imagebackground top="-100" backgroundPosition="BUNDLE" scale="2.19971" useABK="1" safeContainerLocation="persistent" left="0" filename="IMG_20140818_152110.jpeg">

    <relationships>

     <relationship parent="D:/Fotos/2014/Kreta/Urlaub Kreta/2014-08-18/IMG_20140818_152110.jpg" child="IMG_20140818_152110.jpeg" nature="RELATIONSHIP_ONE_TO_ONE_COPY"/>

    </relationships>

   </imagebackground>

  </area>

  <area height="115" zposition="1" shadowIntensity="128" top="1317" rotation="270" width="2650" shadowEnabled="0" shadowAngle="135" shadowDistance="50" areatype="textarea" shadowBlurNew="5" areaAbilities="16400" shadowWidthInMM="4" applySpotColor="0" left="827" alpha="1">

   <border enabled="0" color="#000000" width="1" offset="1" applySpotColor="0"/>

   <text areaTextType="all" isSpineText="1"><![CDATA[<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd"><html><head><meta name="qrichtext" content="1" /><style type="text/css">p, li { white-space: pre-wrap; }</style></head><body style=" font-family:'Bonita'; font-size:16pt; font-weight:400; font-style:normal;"><table border="0" style="-qt-table-type: root; margin-top:23px; margin-bottom:4px; margin-left:4px; margin-right:4px;"><tr><td style="border: none;"><p align="center" style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" color:#ffffff;">                                                                                                                                                       Unser Kreta Urlaub 2014</span></p></td></tr></table></body></html>]]><outline enabled="0" color="#000000" width="1"/>

    <textFormat Alignment="ALIGNHCENTER" VerticalIndentMargin="0" IndentMargin="0" font="Bonita,16,-1,5,50,0,0,0,0,0" foregroundColor="#ffffff" hasOutline="0" backgroundColor="#000000"/>

   </text>

  </area>

**Comment by rbodziony** [comment]
fix file 
change 
...
`<pagenumbering format="0" fontfamily="Arial" bgcolor="#" fontbold="0" textcolor="#000000" position="0" margin="110" fontitalics="0" textstring="%" verticalMargin="50" fontsize="12"> <outline enabled="0" width="1"/> </pagenumbering>
`
...
to 
`<pagenumbering format="0" fontfamily="Arial" bgcolor="#000000" fontbold="0" textcolor="#000000" position="0" margin="110" fontitalics="0" textstring="%" verticalMargin="50" fontsize="12">
 <outline enabled="0" width="1"/>
 </pagenumbering>`

**Comment by Nero6800** [comment]
Great - it works.

Thx and greetings

**Comment by rbodziony** [comment]
pls close issue

**Comment by Nero6800** [comment]
Thx for Help
