### ISSUE TITLE
java.lang.IllegalArgumentException: Width (0) and height (0) cannot be <= 0

### ISSUE THREAD

**Issue by attikov** [albrechtf/mcf2pdf#57]
Looks like you are not the best on handling exceptions and providing meaningful error messages.... 

[ERROR] net.sf.mcf2pdf.Main An exception has occured
java.lang.IllegalArgumentException: Width (0) and height (0) cannot be <= 0
        at java.awt.image.DirectColorModel.createCompatibleWritableRaster(Unknown Source)
        at java.awt.image.BufferedImage.<init>(Unknown Source)
        at net.sf.mcf2pdf.pagebuild.BitmapPageBuilder.addToDocumentBuilder(BitmapPageBuilder.java:66)
        at net.sf.mcf2pdf.Mcf2FoConverter.convert(Mcf2FoConverter.java:211)
        at net.sf.mcf2pdf.Main.main(Main.java:188)

**Comment by albrechtf** [comment]
The software is free. Looks like you are too ignorant to accept that and ask for help in a friendly manner. Well, and you did (obviously) not even manage to read the README.

Leave, and never come back.
