### ISSUE TITLE
Failed to load decorations

### ISSUE THREAD

**Issue by carnager** [albrechtf/mcf2pdf#58]
Trying this tool on a new file i created today and i am getting this:

```
carnager@caprica ~/mcf2pdf/mcf2pdf-0.3.4 > ./mcf2pdf ~/Pictures/THE\ LIFE\ OF\ ARONTHA.mcf bla.pdf                          
[WARN ] net.sf.mcf2pdf.mcfglobals.McfResourceScanner Failed to load decorations from: /home/carnager/bin/cewe/Resources/photofun/decorations/Buchstaben.xml
[WARN ] net.sf.mcf2pdf.mcfglobals.McfResourceScanner Failed to load decorations from: /home/carnager/bin/cewe/Resources/photofun/decorations/cliparts_default.xml
[WARN ] net.sf.mcf2pdf.mcfglobals.McfResourceScanner Failed to load decorations from: /home/carnager/bin/cewe/Resources/photofun/decorations/masks_default.xml
[INFO ] net.sf.mcf2pdf.Mcf2FoConverter Rendering cover...
[ERROR] net.sf.mcf2pdf.Main An exception has occured
java.lang.IllegalArgumentException: Width (0) and height (0) cannot be <= 0
	at java.awt.image.DirectColorModel.createCompatibleWritableRaster(DirectColorModel.java:1016)
	at java.awt.image.BufferedImage.<init>(BufferedImage.java:333)
	at net.sf.mcf2pdf.pagebuild.BitmapPageBuilder.addToDocumentBuilder(BitmapPageBuilder.java:66)
	at net.sf.mcf2pdf.Mcf2FoConverter.convert(Mcf2FoConverter.java:211)
	at net.sf.mcf2pdf.Main.main(Main.java:188)
```

**Comment by rbodziony** [comment]
Check this forked version https://github.com/rbodziony/mcf2pdf/releases/tag/3.7.8
