### ISSUE TITLE
Background not found + java.lang.NullPointerException

### ISSUE THREAD

**Issue by pls2helpout** [albrechtf/mcf2pdf#60]
I have an issue with mcf2pdf.
I cant create a PDF file. 
I have tried out several versions of mcf2pdf (including your Snapshot versions).
I have created my mcf file with the CEWE Software Version 6.4.3.
I am using your mcf2pdf Version 0.3.6 Snapshot for Windows.
My error message is:

[INFO ] net.sf.mcf2pdf.Mcf2FoConverter Rendering cover...
[WARN ] net.sf.mcf2pdf.pagebuild.PageBackground Background not found for page 0: fullcoverpage_landscape
[WARN ] net.sf.mcf2pdf.pagebuild.PageBackground Background not found for page 0: fullcoverpage_with_text_landscape
[ERROR] net.sf.mcf2pdf.Main An exception has occured
java.lang.NullPointerException
        at java.util.regex.Matcher.getTextLength(Unknown Source)
        at java.util.regex.Matcher.reset(Unknown Source)
        at java.util.regex.Matcher.<init>(Unknown Source)
        at java.util.regex.Pattern.matcher(Unknown Source)
        at net.sf.mcf2pdf.pagebuild.PageRenderContext.getClipart(PageRenderContext.java:126)
        at net.sf.mcf2pdf.pagebuild.PageClipart.renderAsBitmap(PageClipart.java:51)
        at net.sf.mcf2pdf.pagebuild.BitmapPageBuilder.addToDocumentBuilder(BitmapPageBuilder.java:75)
        at net.sf.mcf2pdf.Mcf2FoConverter.convert(Mcf2FoConverter.java:224)
        at net.sf.mcf2pdf.Main.main(Main.java:202)

**Comment by rbodziony** [comment]
Can you check this https://github.com/rbodziony/mcf2pdf/releases/tag/3.7.8 and provide debug output?
