### ISSUE TITLE
An exception has occured java.lang.IllegalArgumentException: Width (0) and height (0) cannot be <= 0

### ISSUE THREAD

**Issue by therightdirk** [albrechtf/mcf2pdf#64]
Hi,
I use Cewe 7.0.1 and mcf2pdf0.3.7.
I receive the following message below.
Any idea what I can do?
Thanks

[INFO ] net.sf.mcf2pdf.Mcf2FoConverter Rendering cover...
[WARN ] net.sf.mcf2pdf.pagebuild.PageBackground Background not found for page 0: raster_landscape_middle_cover_full_000200
[ERROR] net.sf.mcf2pdf.Main An exception has occured
java.lang.IllegalArgumentException: Width (0) and height (0) cannot be <= 0
        at java.awt.image.DirectColorModel.createCompatibleWritableRaster(Unknown Source)
        at java.awt.image.BufferedImage.<init>(Unknown Source)
        at net.sf.mcf2pdf.pagebuild.PageText.renderAsBitmap(PageText.java:215)
        at net.sf.mcf2pdf.pagebuild.BitmapPageBuilder.addToDocumentBuilder(BitmapPageBuilder.java:75)
        at net.sf.mcf2pdf.Mcf2FoConverter.convert(Mcf2FoConverter.java:224)
        at net.sf.mcf2pdf.Main.main(Main.java:202)

**Comment by abonne01** [comment]
Hello,

I have the same error (was with pixum, latest version)

I ran program in debug mode :
```
[DEBUG] net.sf.mcf2pdf.Mcf2FoConverter Adding product catalogue found in C:\PROGRA~1\pixum\univer~1\Resources\products\TS101.xml
[DEBUG] net.sf.mcf2pdf.Mcf2FoConverter Checking XML file for product catalogue: C:\PROGRA~1\pixum\univer~1\Resources\products\TS102.xml
[DEBUG] net.sf.mcf2pdf.Mcf2FoConverter Adding product catalogue found in C:\PROGRA~1\pixum\univer~1\Resources\products\TS102.xml
[DEBUG] net.sf.mcf2pdf.Mcf2FoConverter Searching for MCF resources in [C:\PROGRA~1\pixum\univer~1\Resources, C:\ProgramData\tmp, C:\ProgramData\hps]
[DEBUG] net.sf.mcf2pdf.Mcf2FoConverter Reading MCF file
[DEBUG] net.sf.mcf2pdf.Mcf2FoConverter Preparing temporary working directory
[INFO ] net.sf.mcf2pdf.Mcf2FoConverter Rendering cover...
[DEBUG] net.sf.mcf2pdf.pagebuild.BitmapPageBuilder Creating full page image from page elements
[ERROR] net.sf.mcf2pdf.Main An exception has occured
java.lang.IllegalArgumentException: Width (0) and height (0) cannot be <= 0
        at java.awt.image.DirectColorModel.createCompatibleWritableRaster(Unknown Source)
        at java.awt.image.BufferedImage.<init>(Unknown Source)
        at net.sf.mcf2pdf.pagebuild.BitmapPageBuilder.addToDocumentBuilder(BitmapPageBuilder.java:66)
        at net.sf.mcf2pdf.Mcf2FoConverter.convert(Mcf2FoConverter.java:211)
        at net.sf.mcf2pdf.Main.main(Main.java:188)

```

**Comment by sxt643** [comment]
Hi, I get exactly the same error and stack trace. Unsure of a solution.

**Comment by hubert-grininger** [comment]
+1
